name: CI

on:
  workflow_dispatch:

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
        with:
          version: "1.28.0"
